// server/routes/oraclePulseRoutes.js
// Oracle Pulse — community-level observation on the Tracker hero screen
// Reads from CommunityPulse collection (generated by communityPulseEngine)
// Same observation served to ALL users — no per-user generation, no AI calls on request

const express = require('express');
const router = express.Router();
const { getLatestPulse } = require('../services/communityPulseEngine');

// Static fallback when no pulses exist yet
const FALLBACK_OBSERVATION = 'The community is growing. More data sharpens every observation.';

// ============================================================
// GET /api/oracle/pulse
// Returns the latest community observation for ALL users
// ============================================================
router.get('/', async (req, res) => {
  try {
    const pulse = await getLatestPulse();

    if (pulse) {
      return res.json({
        observation: pulse.headline,
        body: pulse.body,
        pulseId: pulse._id.toString(),
        trigger: pulse.trigger
      });
    }

    // No pulses generated yet — return static fallback
    return res.json({
      observation: FALLBACK_OBSERVATION,
      body: null,
      pulseId: null,
      trigger: null
    });

  } catch (err) {
    console.error('[OraclePulse] Error:', err.message);
    res.status(500).json({ error: 'Failed to fetch observation' });
  }
});

module.exports = router;
