// server/models/CommunityPulse.js
// Shared community-level Oracle observations
// One pulse served to ALL users (replaces per-user oraclePulse on User model)
// Generated by communityPulseEngine when Oracle detects something worth saying

const mongoose = require('mongoose');

const communityPulseSchema = new mongoose.Schema({
  // Short observation for app hero screen (≤25 words)
  headline: {
    type: String,
    required: true
  },

  // Full observation for Discord embed (100-150 words)
  body: {
    type: String,
    required: true
  },

  // What triggered this observation
  trigger: {
    type: String,
    enum: [
      'discord_anomaly',       // Topic spike in Discord (from detectAnomaly)
      'relapse_spike',         // Unusual relapse cluster
      'topic_cluster',         // Multiple users independently asking Oracle same thing
      'benefit_shift',         // Community-wide benefit score shift
      'milestone',             // Community milestone (streak record, user count)
      'reddit_hot_post',       // r/semenretention post with notable engagement vs baseline
      'reddit_theme_surge',    // Theme frequency on Reddit spiked vs prior week
      'cross_source',          // Same theme surfacing across 2+ sources at once
      'daily_fallback',        // App-only daily pulse when no real triggers fire (never posted to Discord)
      'manual'                 // Admin-triggered via !pulse-generate
    ],
    required: true
  },

  // Raw data that triggered the observation (for audit/debugging)
  triggerData: {
    type: mongoose.Schema.Types.Mixed
  },

  // ── Fingerprint fields used by the repetition guard ──
  // Filled in at generation time so future pulses can avoid repeating shape, vocab, sources

  // Embedding of headline+body for cosine-similarity novelty check
  embedding: { type: [Number], default: undefined },

  // Which sources the pulse cited (reddit, discord, youtube_own, youtube_niche, inapp, lunar, rag)
  sourcesCited: [{ type: String }],

  // Lead source — the one referenced first in the headline/body
  leadSource: { type: String, default: '' },

  // Wisdom tradition referenced (egyptian, taoist, vedic, hermetic, scientific, etc.)
  traditionCited: { type: String, default: '' },

  // First five words of the headline — used to ban opening-phrase reuse
  openingPhrase: { type: String, default: '' },

  // Key nouns the model leaned on (magnetism, threshold, kundalini, etc.) — cooldown list
  keyNouns: [{ type: String }],

  // Tonal register (celebratory, concerning, suspicious, mundane, contrarian, deadpan, urgent, reverent, dryly_humorous)
  tone: { type: String, default: '' },

  // Discord delivery tracking
  postedToDiscord: {
    type: Boolean,
    default: false
  },
  discordMessageId: String

}, { timestamps: true });

// Fetch latest pulse quickly
communityPulseSchema.index({ createdAt: -1 });

// Auto-delete after 90 days to keep collection lean
communityPulseSchema.index({ createdAt: 1 }, { expireAfterSeconds: 90 * 24 * 60 * 60 });

module.exports = mongoose.model('CommunityPulse', communityPulseSchema);
