// server/models/User.js
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: String,
  email: String,
  googleId: String,
  discordId: String,
  discordAvatar: String,
  discordDisplayName: String, // What people see in Discord (global_name)
  discordOracleSync: { type: Boolean, default: true }, // Oracle shares context across app & Discord
  timezone: { type: String, default: '' }, // IANA timezone (e.g. 'America/New_York') — set by app on each Oracle use
  country: { type: String, default: '' }, // ISO 3166-1 alpha-2 country code (e.g. 'US', 'NG', 'GB')
  
  // Ban system — set via admin cockpit or Render shell
  banned: { type: Boolean, default: false },
  bannedAt: { type: Date, default: null },
  bannedReason: { type: String, default: null },
  
  startDate: Date,
  
  // NEW: Birth date for Energy Almanac calculations (numerology, Chinese zodiac)
  birthDate: Date,
  
  currentStreak: { type: Number, default: 0 },
  longestStreak: { type: Number, default: 0 },
  wetDreamCount: { type: Number, default: 0 },
  wetDreams: [{
    date: Date,
    streakDay: Number,
    moonPhase: String,
    moonIllumination: Number
  }],
  lastWetDream: Date,
  lastRelapse: String,
  lastTrigger: String,
  relapseCount: { type: Number, default: 0 },
  isPremium: { type: Boolean, default: false },
  hasSeenOnboarding: { type: Boolean, default: false },
  needsOracleIntro: { type: Boolean, default: true },
  badges: [{ id: Number, name: String, earned: Boolean, date: Date }],
  benefitTracking: [{ 
    date: Date, 
    energy: Number, 
    focus: Number, 
    confidence: Number, 
    aura: Number, 
    sleep: Number, 
    workout: Number,
    anxiety: Number,
    mood: Number,
    clarity: Number,
    processing: Number,
    streakDay: Number
  }],
  emotionalTracking: [{ 
    date: Date, 
    day: Number, 
    phase: Number, 
    anxiety: Number, 
    moodStability: Number, 
    mentalClarity: Number, 
    emotionalProcessing: Number 
  }],
  emotionalLog: [{ 
    date: Date, 
    day: Number, 
    phase: Number, 
    anxiety: Number, 
    mood: Number, 
    clarity: Number, 
    processing: Number 
  }],
  streakHistory: [{ 
    id: Number, 
    start: Date, 
    end: Date, 
    days: Number, 
    reason: String, 
    trigger: String 
  }],
  urgeToolUsage: [{ date: Date, tool: String, effective: Boolean }],
  urgeLog: [{ 
    date: Date, 
    intensity: Number, 
    trigger: String, 
    toolUsed: String, 
    overcame: Boolean 
  }],
  
  // Discord Integration
  discordUsername: { type: String, default: '' },
  showOnLeaderboard: { type: Boolean, default: false },
  announceDiscordMilestones: { type: Boolean, default: false },
  
  // Mentor System Fields
  mentorEligible: { type: Boolean, default: false },
  verifiedMentor: { type: Boolean, default: false },
  mentorStatus: { 
    type: String, 
    enum: ['available', 'busy', 'inactive'], 
    default: 'inactive' 
  },
  lastMilestoneAnnounced: { type: Number, default: 0 },
  
  // General
  notes: { type: Object, default: {} },
  
  // Oracle Memory - observation notes from AI conversations
  // Capped at 20, oldest rolls off. Generated by Haiku after each chat.
  oracleNotes: [{
    date: { type: Date, default: Date.now },
    streakDay: Number,
    note: { type: String, maxlength: 2000 },
    source: { type: String, enum: ['app', 'discord'], default: 'app' }
  }],

  // ML Risk Snapshot - latest prediction from frontend TensorFlow model
  mlRiskSnapshot: {
    riskScore: Number,       // 0-1 probability
    riskLevel: String,       // 'low', 'moderate', 'elevated', 'high'
    topFactors: [String],    // e.g. ['evening_hours', 'low_energy', 'weekend']
    updatedAt: Date
  },
  
  // Streak display preference — Oracle's Gold color (premium/OG only)
  streakColorGold: { type: Boolean, default: false },
  
  // Oracle Pulse — cached daily observation on Tracker
  oraclePulse: {
    text: String,
    date: String,           // "yyyy-MM-dd" cache key
    generatedAt: Date
  },
  
  // Theme preference
  theme: { type: String, enum: ['dark', 'light'], default: 'dark' },
  
  // Password Reset
  resetPasswordToken: { type: String, default: null },
  resetPasswordExpires: { type: Date, default: null },
  
  // ============================================
  // SUBSCRIPTION & PAYMENT SYSTEM
  // ============================================
  subscription: {
    // Status determines access level
    // 'none'          = never subscribed (default for new users)
    // 'trial'         = 7-day free trial active
    // 'active'        = paying subscriber
    // 'canceled'      = canceled but still has access until period end
    // 'expired'       = trial or subscription ended, no access
    // 'grandfathered'  = lifetime free access (Discord OG members)
    status: { 
      type: String, 
      enum: ['none', 'trial', 'active', 'canceled', 'expired', 'grandfathered', 'banned'], 
      default: 'none' 
    },
    
    // Plan type
    plan: { 
      type: String, 
      enum: ['none', 'monthly', 'yearly', 'lifetime'], 
      default: 'none' 
    },
    
    // Subscription tier — determines Oracle message limit
    // 'practitioner' = $8/mo or $80/yr (3 Oracle/day)
    // 'ascended'     = $17/mo or $170/yr (9 Oracle/day)
    tier: {
      type: String,
      enum: ['practitioner', 'ascended'],
      default: 'practitioner'
    },
    
    // Stripe identifiers
    stripeCustomerId: { type: String, default: null },
    stripeSubscriptionId: { type: String, default: null },
    
    // Trial tracking
    trialStartDate: { type: Date, default: null },
    trialEndDate: { type: Date, default: null },
    
    // Billing cycle
    currentPeriodStart: { type: Date, default: null },
    currentPeriodEnd: { type: Date, default: null },
    
    // Cancellation
    cancelAtPeriodEnd: { type: Boolean, default: false },
    canceledAt: { type: Date, default: null },
    
    // Grandfather tracking
    grandfatheredAt: { type: Date, default: null },
    grandfatheredReason: { type: String, default: null } // 'discord_og', 'manual', etc.
  },
  
  // Notification preferences
  notificationPreferences: {
    type: Object,
    default: {
      quietHoursEnabled: false,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
      types: {
        milestones: true,
        urgeSupport: true,
        weeklyProgress: true
      },
      dailyReminderEnabled: true,
      dailyReminderTime: '20:00'
    }
  },
  
  // AI Chat Usage Tracking
  aiUsage: {
    type: {
      date: String,
      count: { type: Number, default: 0 },
      lifetimeCount: { type: Number, default: 0 },
      lastUsed: Date,
      weekStart: { type: String, default: '' },
      weeklyCount: { type: Number, default: 0 },
      lastIP: { type: String, default: '' }
    },
    default: {
      date: '',
      count: 0,
      lifetimeCount: 0,
      lastUsed: null,
      weekStart: '',
      weeklyCount: 0,
      lastIP: ''
    }
  },
  
  // Free Oracle access until this date (inclusive, checked as now < freeAccessUntil)
  // Usage still counts toward lifetimeCount but daily/weekly limits are bypassed.
  // Set via Render shell for customer service credits. Reusable for any user.
  freeAccessUntil: { type: Date, default: null },
  
  // Discord Oracle lifetime counter — mirrors aiUsage.lifetimeCount but for Discord bot messages
  // Incremented by discord-bot.js recordUsage(). OracleUsage collection auto-deletes after 7d,
  // so this is the only persistent record of total Discord Oracle messages.
  discordOracleLifetime: { type: Number, default: 0 },
  
  // Daily Transmission Cache
  // Stores the AI-generated transmission for the current day
  dailyTransmission: {
    text: { type: String, default: '' },
    generatedAt: { type: Date },
    forStreak: { type: Number, default: 0 },
    phase: { type: String, default: '' }
  },

  // Feedback Replies — admin responses to user-submitted feedback (bugs, etc).
  // Surfaced to the user as a "Transmission" sheet on app load. One-shot:
  // user acknowledges, gets dismissed forever. Pushed by admin via
  // /api/feedback-replies/admin/send.
  feedbackReplies: [{
    message: { type: String, required: true, maxlength: 2000 },
    feedbackText: { type: String, default: '' },
    feedbackType: { type: String, default: 'bug' },
    status: { type: String, enum: ['fixed', 'acknowledged'], default: 'fixed' },
    createdAt: { type: Date, default: Date.now },
    acknowledgedAt: { type: Date, default: null }
  }],
  
  // Peak State Recordings — messages from peak states shown during crisis
  peakRecordings: [{
    message: String,
    date: Date,
    streakDay: Number,
    avgScore: Number
  }],
  
  // Workout Log — exercise data for spermatogenesis/lifting correlation
  workoutLog: [{
    date: Date,
    streakDay: Number,
    spermaDay: Number,        // position in 72-day cycle (for correlation)
    spermaCycle: Number,       // which cycle number (for cross-cycle comparison)
    exercises: [{
      name: String,            // freeform, e.g. "Bench Press"
      weight: Number,          // lbs
      sets: Number,
      reps: Number,
      restMinutes: Number      // e.g. 3.5 for 3min 30sec rest
    }]
  }],
  
  // Mind Program (Based30) — 30-night subliminal audio progress
  mindProgram: {
    nightsCompleted: { type: Number, default: 0 },
    startDate: { type: String, default: null },
    lastConfirmedDate: { type: String, default: null },
    isComplete: { type: Boolean, default: false }
  },
  
  // Week View Metric Preferences — synced across devices
  weekMetrics: {
    type: [String],
    default: ['energy', 'focus', 'confidence']
  }
  
}, {
  timestamps: true
});

// ============================================
// VIRTUAL: Computed premium status
// Returns true if user has active access (trial, active, canceled-but-not-expired, or grandfathered)
// ============================================
userSchema.virtual('hasPremiumAccess').get(function() {
  if (this.banned) return false;
  const sub = this.subscription;
  if (!sub) return false;
  
  const now = new Date();
  
  switch (sub.status) {
    case 'grandfathered':
      return true;
    case 'active':
      return true;
    case 'trial':
      return sub.trialEndDate ? now < sub.trialEndDate : false;
    case 'canceled':
      // Still has access until period end
      return sub.currentPeriodEnd ? now < sub.currentPeriodEnd : false;
    case 'expired':
    case 'none':
    default:
      return false;
  }
});

// Ensure virtuals are included in JSON/Object output
userSchema.set('toJSON', { virtuals: true });
userSchema.set('toObject', { virtuals: true });

// Indexes for efficient queries
userSchema.index({ showOnLeaderboard: 1, currentStreak: -1 });
userSchema.index({ mentorEligible: 1, verifiedMentor: 1 });
userSchema.index({ discordId: 1 });
userSchema.index({ googleId: 1 });
userSchema.index({ email: 1 });
userSchema.index({ 'subscription.status': 1 });
userSchema.index({ 'subscription.stripeCustomerId': 1 });
userSchema.index({ 'aiUsage.lastIP': 1 });

const User = mongoose.model('User', userSchema);

module.exports = User;
